sudo: required
services:
  - docker

before_install:
  - docker build -t aacaeirojr/react-dmc-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aacaeirojr/react-dmc-test npm test -- --coverage

after_success:
  - docker built -t aacaeirojr/multi-client ./client
  - docker built -t aacaeirojr/multi-nginx ./nginx
  - docker built -t aacaeirojr/multi-server ./server
  - docker built -t aacaeirojr/multi-worker ./worker

  # Docker Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Docker Push
  - docker push aacaeirojr/multi-client
  - docker push aacaeirojr/multi-nginx
  - docker push aacaeirojr/multi-server
  - docker push aacaeirojr/multi-worker
